export const ONBOARD = 'ONBOARD';

export const FRIENDS_REQUEST = 'FRIENDS_REQUEST';
export const MY_FRIENDS_REQUEST = 'MY_FRIENDS_REQUEST';
export const STOP_FRIENDS_REQUEST = 'STOP_FRIENDS_REQUEST';
export const STOP_MY_FRIENDS_REQUEST = 'STOP_MY_FRIENDS_REQUEST';
export const FRIEND_ADDED = 'FRIEND_ADDED';
export const FRIEND_CHANGED = 'FRIEND_CHANGED';
export const MY_FRIEND_ADDED = 'MY_FRIEND_ADDED';
export const MY_FRIEND_REMOVED = 'MY_FRIEND_REMOVED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const RECEIVE_USERNAME = 'RECEIVE_USERNAME';

export const SET_FILTER = 'SET_FILTER';

export const REQUEST_FETCH_HOTGIRLS = 'REQUEST_FETCH_HOTGIRLS';
export const STOP_REQUEST_HOTGIRLS = 'STOP_REQUEST_HOTGIRLS';
export const REMOVE_HOTGIRL = 'REMOVE_HOTGIRL';
export const HOTGIRL_CHANGED = 'HOTGIRL_CHANGED';
export const FETCH_HOTGIRLS_SUCCESS = 'FETCH_HOTGIRLS_SUCCESS';
export const FETCH_HOTGIRLS_FAIL = 'FETCH_HOTGIRLS_FAIl';
export const FETCH_HOTGIRLS_PENDING = 'FETCH_HOTGIRLS_PENDING';

export const REQUEST_HOTGIRL_COMMENTS = 'REQUEST_HOTGIRL_COMMENTS';
export const STOP_REQUEST_HOTGIRL_COMMENTS = 'STOP_REQUEST_HOTGIRL_COMMENTS';
export const NEW_COMMENT = 'NEW_COMMENT';
