// ROOT NAVIGATOR
export const AUTH_LOADING_SCREEN = 'AUTH_SCREEN';
export const ONBOARD_SCREEN = 'ONBOARD_SCREEN';
export const MAIN_SCREEN = 'MAIN_SCREEN';

// MAIN NAVIGATOR
export const FRIENDS_SCREEN = 'FRIENDS_SCREEN';
export const SWIPE_HOTGIRL_SCREEN = 'SWIPE_HOTGIRL_SCREEN';
