export const FILTER_MODE_NEW_FRIENDS = 'FILTER_MODE_NEW_FRIENDS';
export const FILTER_MODE_MY_FRIENDS = 'FILTER_MODE_MY_FRIENDS';
export const VERTICAL_LIST_MODE_FRIEND = 'VERTICAL_LIST_MODE_FRIEND';
export const VERTICAL_LIST_MODE_COMMENT = 'VERTICAL_LIST_MODE_COMMENT';
